services:
  db:
    image: postgres:17-alpine
    container_name: admin-db
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminpass123
      POSTGRES_DB: admindb
    volumes:
      - admin-postgres-data:/var/lib/postgresql/data
    ports: 
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminuser -d admindb"]
      interval: 5s
      retries: 10
    restart:  unless-stopped
    networks: 
      - microservices-network

  api:
    build:  .
    container_name: admin-api
    environment:
      - APP_ENV=docker
      - AUTH_SERVICE_URL=http://auth-api:8000
      - DATABASE_URL=postgresql+psycopg2://adminuser:adminpass123@admin-db:5432/admindb
      - RABBIT_URL=amqps://ykvaygzy:Kg8o0HCEw9hRygtPpnQ3bjWv7N9KU0xZ@stingray.rmq.cloudamqp.com/ykvaygzy
      - SECRET_KEY=JAMIESKEY
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8000"
    restart: unless-stopped
    networks:
      - microservices-network

  worker:
    build: . 
    container_name: admin-worker
    environment:
      - APP_ENV=docker
      - DATABASE_URL=postgresql+psycopg2://adminuser:adminpass123@admin-db:5432/admindb
      - RABBIT_URL=amqps://ykvaygzy:Kg8o0HCEw9hRygtPpnQ3bjWv7N9KU0xZ@stingray.rmq.cloudamqp.com/ykvaygzy
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 10 && python worker.py"
    restart: unless-stopped
    networks: 
      - microservices-network

volumes:
  admin-postgres-data:

networks:
  microservices-network:
    external: true